modLoader = "bm_upwards"
loaderVersion = "a"
license = "${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" # https://docs.neoforge.net/docs/misc/updatechecker/
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/
logoFile="logo.png"
#credits=""
authors = "${mod_authors}"

description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required" # "required", "optional", "incompatible" or "discouraged"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId="breadmod"
type = "required"
reason="This mod extends Bread Mod."
versionRange="[1.1.0,)"
ordering="AFTER"
side="BOTH"